server:
    port: 8000

spring:
    application:
        name: customer
    datasource:
        username: 'praveenukkoji'
        url: jdbc:postgresql://postgres:5432/customer
        password: 'password'
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: 'true'
        hibernate:
            ddl-auto: update
        show-sql: 'true'
    zipkin:
        base-url: http://zipkin:9411
    rabbitmq:
        addresses: rabbitmq:5672

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://eureka-server:8761/eureka