server:
    port: 8000

spring:
    application:
        name: customer
    datasource:
        username: 'praveenukkoji'
        url: jdbc:postgresql://localhost:5433/customer
        password: 'password'
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: 'true'
        hibernate:
            ddl-auto: update
        show-sql: 'true'

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka