server:
    port: 8002

spring:
    application:
        name: notification
    datasource:
        username: 'praveenukkoji'
        url: jdbc:postgresql://localhost:5433/notification
        password: 'password'
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: 'true'
        hibernate:
            ddl-auto: update
        show-sql: 'true'
    zipkin:
        base-url: http://localhost:9411
    rabbitmq:
        addresses: localhost:5672

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka

rabbitmq:
    exchanges:
        internal: internal.exchange
    queues:
        notification: notification.queue
    routing-keys:
        internal-notification: internal.notification.routing-key