server:
    port: 8001

spring:
    application:
        name: fraud
    datasource:
        username: 'praveenukkoji'
        url: jdbc:postgresql://localhost:5433/fraud
        password: 'password'
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: 'true'
        hibernate:
            ddl-auto: update
        show-sql: 'true'
    zipkin:
        base-url: http://localhost:9411

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka